title: Sem04
description: "Kubernetes und CI/CD!"
remote_theme: just-the-docs/just-the-docs

url: https://krkiso.github.io/SEM4/

aux_links:
  JIRA Projekt: https://sem4-mh.atlassian.net/jira/software/projects/SCRUM/boards/1/timeline

footer_content: "2024 Marc Hofstetter Sem04 für Technische Berufsschule Zürich, Lehrgang Cloud Native Engineer"